# Welcome to Plus!
#
# This config file affects your whole blog.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
title:              Gerit Wagner
description:        Curriculum Vitae
url:                "https://geritwagner.github.io" # Site base hostname & protocol, e.g. http://example.com
baseurl:            "/website" # Site subpath, e.g. /blog
# logo_image:
#   light:            # logo-light.png
#   dark:             # logo-dark.png
permalink:          /:title/ # Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
date_format:        "%b %-d, %Y" # refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
post_assets:        /assets/img/ # Path to post content assets directory i.e post images, pdfs etc

google_analytics:   # Google analytics code, get your code here https://www.google.com/analytics/

footer:             # Default footer image settings
    copyright:      Copyright 2018 Gerit Wagner
    impressum:      /impressum/

# Style settings
navbar:
  background:       "#ffffff" # color value e.g. "#28a5f5"
  style:            dark # text color, dark or light
  sticky:           true
  animation: true
  transparent: true

header:
    background_image: header.jpg
    background_align: top

# Author settings
author:
  name:           Gerit Wagner
  image:          gerit_wagner.jpg
  bio:            >
                  Gerit Wagner currently works at the Institut für Wirtschaftsinformatik, Universität Regensburg.
                  Gerit does research in Information Science and Information Systems (Business Informatics).

  email:          gerit.wagner@wiwi.uni-regensburg.de
  researchgate:   https://www.researchgate.net/profile/Gerit_Wagner2
  cv:             gerit_wagner_cv.pdf
  orcid:
    url:          https://orcid.org/0000-0003-3926-7717

print:
  email:          gerit.wagner@posteo.de
  address:        Galgenbergstr. 12a 3.10 <br> 93053 Regensburg
  phone:          +49 (941) 943 5743
  mobile:         +49 (178) 1345693

# Social buttons
social_networks:
  email:          gerit.wagner@wiwi.uni-regensburg.de
  researchgate:   https://www.researchgate.net/profile/Gerit_Wagner2


# Build settings
markdown:           kramdown
highlighter:        rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - CHANGELOG
  - LICENSE
  - README
  - vendor  # https://github.com/jekyll/jekyll/issues/2938 let Jekyll skip these view template folders.

sass:
  style:            compressed

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
